# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE are ignored when building from the
# command line, check build.gradle files instead.

# When configured, Gradle will run in offline mode and disallow refreshing of
# dependencies from the internet.
org.gradle.offline=false

# Enables namespacing of each library's R class so that its R class includes only the
# resources declared in the library itself and sees the resources of its dependencies
# declared as public there.
android.nonTransitiveRClass=true

# Enable parallel builds
org.gradle.parallel=true

# Enable build cache
org.gradle.caching=true
